"use client";

import { keepPreviousData, useQuery, useQueryClient } from "@tanstack/react-query";
import { LoaderCircleIcon, PencilIcon, PlusIcon, RefreshCwIcon, Trash2Icon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { z } from "zod";

import { DataTable, type Column } from "@/components/data-table";
import { FilterBar, type FilterDef } from "@/components/filter-bar";
import { Field, Form, FormActions, FormBanner, FormGrid, SubmitButton, useApiForm } from "@/components/form";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useListParams } from "@/hooks/use-list-params";
import { ApiError, api, employeeKeys, leaveBalanceKeys, type LeaveBalance, type RecomputeResult } from "@/lib/api";

const dayText = (value: number) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(value);
const columns: readonly Column<LeaveBalance>[] = [
  { key: "employeeId", header: "Employee", sortable: true, cell: (row) => <span className="font-medium">{row.employee.firstName} {row.employee.lastName}</span> },
  { key: "leaveTypeId", header: "Leave type", sortable: true, cell: (row) => row.leaveType.typeName },
  { key: "year", header: "Year", sortable: true, cell: (row) => row.year },
  { key: "allocatedDays", header: "Allocated", sortable: true, align: "end", cell: (row) => dayText(row.allocatedDays) },
  { key: "carried", header: "Carried", align: "end", cell: (row) => dayText(row.carriedForwardDays) },
  { key: "usedDays", header: "Used", sortable: true, align: "end", cell: (row) => dayText(row.usedDays) },
  { key: "remaining", header: "Remaining", align: "end", cell: (row) => dayText(row.remainingDays) },
  { key: "pending", header: "Pending", align: "end", cell: (row) => dayText(row.pendingDays) },
  { key: "available", header: "Available", align: "end", cell: (row) => <strong>{dayText(row.availableDays)}</strong> },
];

const allocationSchema = z.object({ employeeId: z.string(), leaveTypeId: z.string(), year: z.string().regex(/^\d{4}$/, "Enter a four-digit year"), allocatedDays: z.string().regex(/^\d+(\.\d{1,2})?$/, "Use up to two decimal places") });
type AllocationValues = z.infer<typeof allocationSchema>;
function allocationDefaults(balance?: LeaveBalance, employeeId?: number, year?: number): AllocationValues { return { employeeId: balance ? String(balance.employeeId) : employeeId ? String(employeeId) : "", leaveTypeId: balance ? String(balance.leaveTypeId) : "", year: String(balance?.year ?? year ?? new Date().getFullYear()), allocatedDays: String(balance?.allocatedDays ?? "") }; }

function AllocationDialog({ balance, defaultEmployeeId, defaultYear, trigger }: { balance?: LeaveBalance; defaultEmployeeId?: number; defaultYear?: number; trigger: React.ReactNode }) {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const employees = useQuery({ ...api.employees.list({ pageSize: 100, sort: "lastName" }), enabled: open && !balance }); const types = useQuery({ ...api.leaveTypes.list({ pageSize: 100, sort: "typeName" }), enabled: open && !balance });
  const form = useApiForm<AllocationValues, LeaveBalance>({ schema: allocationSchema, defaultValues: allocationDefaults(balance, defaultEmployeeId, defaultYear), fields: ["employeeId", "leaveTypeId", "year", "allocatedDays"], submit: (values) => balance ? api.leaveBalances.update(balance.leaveBalanceId, { allocatedDays: Number(values.allocatedDays) }) : api.leaveBalances.create({ employeeId: Number(values.employeeId), leaveTypeId: Number(values.leaveTypeId), year: Number(values.year), allocatedDays: Number(values.allocatedDays) }), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: leaveBalanceKeys.all }), queryClient.invalidateQueries({ queryKey: employeeKeys.all })]); setOpen(false); toast.success(balance ? "Allocation updated" : "Allocation created"); } });
  const { register } = form.form;
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); form.setFormError(null); if (next) form.form.reset(allocationDefaults(balance, defaultEmployeeId, defaultYear)); }}><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{balance ? "Edit allocation" : "New allocation"}</DialogTitle><DialogDescription>Remaining, pending and available days are calculated by the API and cannot be edited.</DialogDescription></DialogHeader><Form api={form}><FormGrid>{!balance && <><Field name="employeeId" label="Employee" required>{(control) => <Select value={form.form.watch("employeeId") || undefined} onValueChange={(value) => form.form.setValue("employeeId", value, { shouldValidate: true })}><SelectTrigger {...control} className="w-full"><SelectValue placeholder="Select employee" /></SelectTrigger><SelectContent>{(employees.data?.data ?? []).filter((employee) => employee.status === "ACTIVE").map((employee) => <SelectItem key={employee.employeeId} value={String(employee.employeeId)}>{employee.fullName}</SelectItem>)}</SelectContent></Select>}</Field><Field name="leaveTypeId" label="Leave type" required>{(control) => <Select value={form.form.watch("leaveTypeId") || undefined} onValueChange={(value) => form.form.setValue("leaveTypeId", value, { shouldValidate: true })}><SelectTrigger {...control} className="w-full"><SelectValue placeholder="Select type" /></SelectTrigger><SelectContent>{(types.data?.data ?? []).filter((type) => type.requiresBalance).map((type) => <SelectItem key={type.leaveTypeId} value={String(type.leaveTypeId)}>{type.typeName}</SelectItem>)}</SelectContent></Select>}</Field><Field name="year" label="Year" required>{(control) => <Input {...control} type="number" min={2000} max={2100} {...register("year")} />}</Field></>}<Field name="allocatedDays" label="Allocated days" required>{(control) => <Input {...control} inputMode="decimal" {...register("allocatedDays")} />}</Field></FormGrid><FormActions><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><SubmitButton pending={form.isSubmitting} disabled={!balance && (!form.form.watch("employeeId") || !form.form.watch("leaveTypeId"))}>{balance ? "Save allocation" : "Create allocation"}</SubmitButton></FormActions></Form></DialogContent></Dialog>;
}

function DeleteAllocation({ balance }: { balance: LeaveBalance }) {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  async function remove() { setPending(true); setError(null); try { await api.leaveBalances.remove(balance.leaveBalanceId); await Promise.all([queryClient.invalidateQueries({ queryKey: leaveBalanceKeys.all }), queryClient.invalidateQueries({ queryKey: employeeKeys.all })]); setOpen(false); toast.success("Allocation deleted"); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Allocation could not be deleted."); } finally { setPending(false); } }
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); setError(null); }}><DialogTrigger asChild><Button type="button" variant="ghost" size="icon-sm"><Trash2Icon /><span className="sr-only">Delete</span></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Delete this allocation?</DialogTitle><DialogDescription>Deleting a balance can affect availability reporting. Approved request history is not deleted.</DialogDescription></DialogHeader><FormBanner message={error} /><DialogFooter><Button type="button" variant="outline" disabled={pending} onClick={() => setOpen(false)}>Cancel</Button><Button type="button" variant="destructive" disabled={pending} onClick={() => void remove()}>{pending && <LoaderCircleIcon className="animate-spin" />} Delete allocation</Button></DialogFooter></DialogContent></Dialog>;
}

function InitializeDialog({ year }: { year?: number }) {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [targetYear, setTargetYear] = useState(year ?? new Date().getFullYear()); const [carry, setCarry] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<{ employees: number; leaveTypes: number; created: number; skipped: number } | null>(null);
  async function run() { setPending(true); setError(null); try { const next = await api.leaveBalances.initialize({ year: targetYear, carryForward: carry }); setResult(next); await Promise.all([queryClient.invalidateQueries({ queryKey: leaveBalanceKeys.all }), queryClient.invalidateQueries({ queryKey: employeeKeys.all })]); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Initialization failed."); } finally { setPending(false); } }
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); setError(null); if (!next) setResult(null); }}><DialogTrigger asChild><Button type="button" variant="outline">Initialize year</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Initialize allocation year</DialogTitle><DialogDescription>Create missing tracked balances for active employees. Existing rows are skipped.</DialogDescription></DialogHeader><FormBanner message={error} /><div className="flex flex-col gap-1.5"><Label htmlFor="initialize-year">Year</Label><Input id="initialize-year" type="number" min={2000} max={2100} value={targetYear} onChange={(event) => setTargetYear(Number(event.target.value))} /></div><Label className="flex items-center gap-2 font-normal"><Checkbox checked={carry} onCheckedChange={(value) => setCarry(value === true)} />Carry forward last year’s remaining days</Label>{result && <div className="grid grid-cols-2 gap-2 rounded-lg bg-muted/50 p-3 text-sm"><p>Employees: {result.employees}</p><p>Leave types: {result.leaveTypes}</p><p>Created: {result.created}</p><p>Skipped: {result.skipped}</p></div>}<DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Close</Button><Button type="button" disabled={pending || targetYear < 2000 || targetYear > 2100} onClick={() => void run()}>{pending && <LoaderCircleIcon className="animate-spin" />} Initialize</Button></DialogFooter></DialogContent></Dialog>;
}

function RecomputeDialog({ year }: { year?: number }) {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [targetYear, setTargetYear] = useState(year ? String(year) : ""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<RecomputeResult | null>(null);
  async function run() { setPending(true); setError(null); try { const next = await api.leaveBalances.recompute(targetYear ? { year: Number(targetYear) } : {}); setResult(next); await queryClient.invalidateQueries({ queryKey: leaveBalanceKeys.all }); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Recompute failed."); } finally { setPending(false); } }
  return <Dialog open={open} onOpenChange={(next) => { setOpen(next); setError(null); if (!next) setResult(null); }}><DialogTrigger asChild><Button type="button" variant="outline"><RefreshCwIcon /> Recompute</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Recompute used leave</DialogTitle><DialogDescription>Reconcile used days against approved requests. Leave year blank to check all years.</DialogDescription></DialogHeader><FormBanner message={error} /><div className="flex flex-col gap-1.5"><Label htmlFor="recompute-year">Year (optional)</Label><Input id="recompute-year" type="number" min={2000} max={2100} value={targetYear} onChange={(event) => setTargetYear(event.target.value)} /></div>{result && <div className="rounded-lg bg-muted/50 p-3 text-sm"><p className="font-medium">Checked {result.checked}; corrected {result.corrected}</p>{result.corrections.map((item) => <p key={item.leaveBalanceId} className="text-muted-foreground">#{item.leaveBalanceId}: {item.from} → {item.to}</p>)}</div>}<DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Close</Button><Button type="button" disabled={pending} onClick={() => void run()}>{pending && <LoaderCircleIcon className="animate-spin" />} Recompute</Button></DialogFooter></DialogContent></Dialog>;
}

function positiveId(value: string | undefined): number | undefined { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : undefined; }
function validYear(value: string | undefined): number | undefined { const year = Number(value); return Number.isInteger(year) && year >= 2000 && year <= 2100 ? year : undefined; }

export function HrLeaveBalances() {
  const list = useListParams({ sort: "year", order: "desc" }); const employeeId = positiveId(list.filters.employeeId); const leaveTypeId = positiveId(list.filters.leaveTypeId); const year = validYear(list.filters.year);
  const employees = useQuery(api.employees.list({ pageSize: 100, sort: "lastName" })); const types = useQuery(api.leaveTypes.list({ pageSize: 100, sort: "typeName" })); const query = useQuery({ ...api.leaveBalances.list({ ...list.params, employeeId, leaveTypeId, year }), placeholderData: keepPreviousData });
  const filters: readonly FilterDef[] = [{ kind: "select", key: "employeeId", label: "Employee", allLabel: "All employees", options: (employees.data?.data ?? []).map((employee) => ({ value: String(employee.employeeId), label: employee.fullName })) }, { kind: "select", key: "leaveTypeId", label: "Leave type", allLabel: "All types", options: (types.data?.data ?? []).map((type) => ({ value: String(type.leaveTypeId), label: type.typeName })) }, { kind: "text", key: "year", label: "Year", placeholder: "YYYY" }];
  return <div className="mx-auto flex w-full max-w-content flex-col gap-5 px-4 py-8"><PageHeader title="Leave Allocations" description="Manage allocations; remaining, pending and available days stay service-derived."><AllocationDialog defaultEmployeeId={employeeId} defaultYear={year} trigger={<Button><PlusIcon /> New allocation</Button>} /><InitializeDialog year={year} /><RecomputeDialog year={year} /></PageHeader><FilterBar list={list} filters={filters} search searchPlaceholder="Employee name or email…" /><DataTable columns={columns} query={query} list={list} rowKey={(row) => row.leaveBalanceId} caption="Leave allocations" rowActions={(row) => <div className="flex justify-end gap-1"><AllocationDialog balance={row} trigger={<Button type="button" variant="ghost" size="icon-sm"><PencilIcon /><span className="sr-only">Edit</span></Button>} /><DeleteAllocation balance={row} /></div>} empty={{ title: "No allocations", description: "Initialize a year or create an allocation." }} /></div>;
}
